message="selam, benim Adım cengiz ATİLA"
print(message)
message= message.upper()
print(message)
message= message.lower()
message=message.split()
print(message )
message="??".join(message)
print(message)
index=message.find("cengiz")
print(index)
message=message.replace("cengiz","Han")
print(message)
message=message.center(40,"/")
print(message)